# -*- coding: utf-8 -*-
"""Capstone Project with CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdYNnVeUIecM90XAVZvk8S1Sh3hFT9E4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tensorflow.keras.preprocessing.image import ImageDataGenerator

import os
os.environ['KAGGLE_USERNAME'] = 'lievwurtzel'   # from your profile URL: kaggle.com/<this>
os.environ['KAGGLE_KEY'] = 'KGAT_4a1f0cfa20a4f223979508fb81881d13'

!pip install -q kaggle
!kaggle datasets download -d birdy654/cifake-real-and-ai-generated-synthetic-images
!unzip -q cifake-real-and-ai-generated-synthetic-images.zip -d /content/CIFAKE

import tensorflow as tf
AUTOTUNE = tf.data.AUTOTUNE
IMG = (32, 32); BATCH = 64

train_ds = tf.keras.utils.image_dataset_from_directory(
    '/content/CIFAKE/train', label_mode='binary', image_size=IMG,
    batch_size=BATCH, validation_split=0.2, subset='training', seed=42)
val_ds = tf.keras.utils.image_dataset_from_directory(
    '/content/CIFAKE/train', label_mode='binary', image_size=IMG,
    batch_size=BATCH, validation_split=0.2, subset='validation', seed=42)
test_ds = tf.keras.utils.image_dataset_from_directory(
    '/content/CIFAKE/test', label_mode='binary', image_size=IMG,
    batch_size=BATCH, shuffle=False)

train_ds = train_ds.cache().shuffle(1000).prefetch(AUTOTUNE)
val_ds   = val_ds.cache().prefetch(AUTOTUNE)
test_ds  = test_ds.cache().prefetch(AUTOTUNE)

from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(layers.Input(shape=(32, 32, 3)))
model.add(layers.Rescaling(1./255))
model.add(layers.RandomFlip('horizontal'))

model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add(layers.Conv2D(256, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Dropout(0.25))

model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Dropout(0.25))

model.add(layers.Flatten())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

import pandas as pd
results = []

def log_run(name, model, history):
    test_loss, test_acc = model.evaluate(test_ds, verbose=0)
    val_acc = max(history.history['val_accuracy'])
    results.append({'model': name,
                    'val_acc': round(val_acc, 4),
                    'test_acc': round(test_acc, 4),
                    'epochs_run': len(history.history['loss'])})
    return pd.DataFrame(results)

from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(monitor='val_loss', patience=5,
                           restore_best_weights=True, verbose=1)
history = model.fit(train_ds, validation_data=val_ds, epochs=40,
                    callbacks=[early_stop])

score = model.evaluate(test_ds, verbose=1)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

log_run('wide_64-128-256_long', model, history)

import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
import seaborn as sns
import matplotlib.pyplot as plt

# Predicted probabilities -> 0/1.  Sigmoid output: closer to 1 = REAL
y_prob = model.predict(test_ds)
y_pred = (y_prob >= 0.5).astype(int).flatten()

# True labels. test_ds has shuffle=False, so order is stable and lines up.
y_true = np.concatenate([y.numpy() for _, y in test_ds]).astype(int).flatten()

labels = ['FAKE', 'REAL']    # class 0, class 1
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(5.5, 4.5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=labels, yticklabels=labels, cbar=False,
            annot_kws={'size': 14})
plt.xlabel('Predicted'); plt.ylabel('Actual')
plt.title('Confusion Matrix — CIFAKE test set')
plt.show()

print(classification_report(y_true, y_pred, target_names=labels))

import glob, random
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import ipywidgets as widgets
from IPython.display import display, clear_output

def play_game(test_dir, model, rounds=10, display_size=512):
    pool = ([(f, 'REAL') for f in glob.glob(f'{test_dir}/REAL/*')] +
            [(f, 'FAKE') for f in glob.glob(f'{test_dir}/FAKE/*')])
    random.shuffle(pool)
    S = {'i': 0, 'human': 0, 'machine': 0, 'played': 0}
    name = {0: 'FAKE', 1: 'REAL'}

    img_out, res_out = widgets.Output(), widgets.Output()
    b_real = widgets.Button(description='Real', button_style='success')
    b_fake = widgets.Button(description='Fake', button_style='danger')
    b_skip = widgets.Button(description='Skip')
    b_next = widgets.Button(description='Next ▶', button_style='info', disabled=True)
    controls = widgets.HBox([b_real, b_fake, b_skip, b_next])

    def show_image():
        with img_out:
            clear_output(wait=True)
            path, _ = pool[S['i']]
            img = Image.open(path).convert('RGB')
            plt.figure(figsize=(4, 4))
            plt.imshow(img.resize((display_size, display_size), Image.LANCZOS))
            plt.axis('off'); plt.title(f"Round {S['played']+1} of {rounds}")
            plt.show()

    def toggle(guessing):
        b_real.disabled = b_fake.disabled = b_skip.disabled = not guessing
        b_next.disabled = guessing

    def guess(choice):
        path, truth = pool[S['i']]
        img = Image.open(path).convert('RGB')
        arr = np.array(img.resize((32, 32)), dtype='float32')[None, ...]
        prob = float(model.predict(arr, verbose=0)[0][0])
        m_pred = name[int(prob >= 0.5)]
        h_ok, m_ok = choice == truth, m_pred == truth
        S['human'] += h_ok; S['machine'] += m_ok; S['played'] += 1
        with res_out:
            clear_output(wait=True)
            print(f"Truth:  {truth}")
            print(f"You:    {choice}   {'✓' if h_ok else '✗'}")
            print(f"Model:  {m_pred}  (p={prob:.2f})   {'✓' if m_ok else '✗'}")
            print(f"Score — You: {S['human']}/{S['played']}   Model: {S['machine']}/{S['played']}")
        toggle(False)

    def advance(_=None):
        S['i'] += 1
        if S['played'] >= rounds or S['i'] >= len(pool):
            controls.close()
            with img_out: clear_output()
            with res_out:
                clear_output(wait=True)
                print(f"FINAL — You: {S['human']}/{S['played']}   Model: {S['machine']}/{S['played']}")
        else:
            toggle(True); show_image()

    b_real.on_click(lambda b: guess('REAL'))
    b_fake.on_click(lambda b: guess('FAKE'))
    b_skip.on_click(advance)          # skip: no guess, just move on
    b_next.on_click(advance)

    display(img_out, controls, res_out)
    show_image()

play_game('CIFAKE/test', model, rounds=10)